//General
export type ActionTypes =

    'CHANGE_LAYOUT' |
    "SET_WARNING_VERSION" |
    "REQUEST_ACTION" |
    "ENABLE_LOADER" |
    "DISABLE_LOADER" |
    "LOGIN_REQUEST" |
    "SAVE_GENERAL_REDUCER" |
    "SAVE_PRESIST_REDUCER" |
    "CLEAR_PRESIST_REDUCER" |
    "POPULAR_DOCTOR" | "GET_SPECIALIZATION" |
    "GET_CAR_LIST" |
    "REQUEST_ACTION_LATEST" |
    "GET_NOTIFICATION_LIST" |
    "GET_ALL_FILTER_CARS" |
    "GET_BRANDS" |
    "GET_ALL_CARS" |
    "GET_SHOW_ROOMS" |
    "GET_SHOW_ROOM_CARS" |
    "STORE_ADD_CAR_DATA" |
    "SET_ADVANCED_FILTER" |
    "GET_BRAND_MODALS" |
    "GET_CITIES" |
    "CAR_VIEWS" |
    "SIGN_IN" |
    "SIGN_UP" |
    "LOGOUT" |
    "FORGOT_PASSWORD" |
    "FORGOT_PASSWORD_SEND_OTP" |
    "RESET_PASSWORD" |
    "CHANGE_PASSWORD" |
    "VERIFY_PHONE_NUMBER" |
    "RESEND_OTP" |
    "CONTACT_US" |
    "FAVOURITE_SHOWROOM" |
    "FAVOURITE_CARS" |
    "GET_PROFILE" |
    "UPDATE_PROFILE" |
    "SIMILAR_CARS" |
    "FAVOURITE_SHOWROOMS_LIST" |
    "FAVOURITE_CARS_LIST" |
    "MY_CAR_ADS" |
    "GET_NOT_VIEWD_NOTIFICATION" |
    "ADD_NEW_CAR" |
    "REMOVE_CAR" |
    "EDIT_CAR" |
    "SOCAIL_LOGIN" |
    "APP_SETTINGS" |
    "LOG_ERRORS" |
    "SOLD_CAR" |
    "ADD_DEVICE_NOTIFICATION" |
    "LOGOUT_USER"


export const CHANGE_LAYOUT = "CHANGE_LAYOUT";

export const LOGOUT_USER = "LOGOUT_USER";

export const ADD_DEVICE_NOTIFICATION = "ADD_DEVICE_NOTIFICATION";
export const SOLD_CAR = "SOLD_CAR";
export const LOG_ERRORS = "LOG_ERRORS";
export const SET_WARNING_VERSION = "SET_WARNING_VERSION";
export const APP_SETTINGS = "APP_SETTINGS";
export const SOCAIL_LOGIN = "SOCAIL_LOGIN";
export const EDIT_CAR = "EDIT_CAR";
export const REMOVE_CAR = "REMOVE_CAR";
export const ADD_NEW_CAR = "ADD_NEW_CAR";
export const GET_NOT_VIEWD_NOTIFICATION = "GET_NOT_VIEWD_NOTIFICATION";
export const GET_NOTIFICATION_LIST = "GET_NOTIFICATION_LIST";
export const FAVOURITE_SHOWROOMS_LIST = "FAVOURITE_SHOWROOMS_LIST";
export const FAVOURITE_CARS_LIST = "FAVOURITE_CARS_LIST";
export const MY_CAR_ADS = "MY_CAR_ADS";
export const SIMILAR_CARS = "SIMILAR_CARS";
export const CONTACT_US = "CONTACT_US";
export const FAVOURITE_SHOWROOM = "FAVOURITE_SHOWROOM";
export const FAVOURITE_CARS = "FAVOURITE_CARS";
export const GET_PROFILE = "GET_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const RESEND_OTP = "RESEND_OTP";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_SEND_OTP = "FORGOT_PASSWORD_SEND_OTP";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const VERIFY_PHONE_NUMBER = "VERIFY_PHONE_NUMBER";

export const LOGOUT = "LOGOUT/LOGOUT";
export const SIGN_IN = "CAR_VIEWS/SIGN_IN";
export const SIGN_UP = "SIGN_UP/SIGN_UP";
export const CAR_VIEWS = "CAR_VIEWS/CAR_VIEWS";
export const GET_CITIES = "GET_CITIES/GET_CITIES";

export const STORE_ADD_CAR_DATA = "ADD/STORE_ADD_CAR_DATA";
export const SET_ADVANCED_FILTER = "ADD/SET_ADVANCED_FILTER";
export const GET_BRAND_MODALS = "ADD/GET_BRAND_MODALS";
export const GET_ALL_FILTER_CARS = "ADD/GET_ALL_FILTER_CARS";


export const GET_BRANDS = "ADS/GET_BRANDS";
export const GET_ALL_CARS = "ADS/GET_ALL_CARS";
export const GET_SHOW_ROOMS = "ADS/GET_SHOW_ROOMS";
export const GET_SHOW_ROOM_CARS = "ADS/GET_SHOW_ROOM_CARS";



export const REQUEST_ACTION_LATEST = 'REQUEST_ACTION_LATEST';
//request General Saga
export const REQUEST_ACTION = "REQUEST_ACTION"

//Save General Reducer
export const SAVE_GENERAL_REDUCER = 'SAVE_GENERAL_REDUCER';

//Save Presist Reducer
export const SAVE_PRESIST_REDUCER = 'SAVE_PRESIST_REDUCER';
//Clear Presist Reducer
export const CLEAR_PRESIST_REDUCER = "CLEAR_PRESIST_REDUCER";

export const SET_DOWNLOADED_PDF = "SET_DOWNLOADED_PDF";

//loaders
export const ENABLE_LOADER = 'ENABLE_LOADER';
export const DISABLE_LOADER = 'DISABLE_LOADER';

//login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
